build:
	go build -o terraform-provider-azvmcapability

install:
	mkdir -p ~/.terraform.d/plugins/example/azvmcapability/0.1.0/linux_amd64
	mv terraform-provider-azvmcapability ~/.terraform.d/plugins/example/azvmcapability/0.1.0/linux_amd64/terraform-provider-example_azvmcapability
